### ISSUE TITLE
Not working on Mobile

### ISSUE THREAD

**Issue by ruben-kasaz** [rayandrews/react-native-web-modal#23] opened 2020-01-02 11:13 UTC
Hello everyone !

I am using `react-native-web-modal `on an Expo Web project.
In the web side, it's totally working, but when I try on mobile, I have this issue : 

![81249238_1029179477437646_8631771602142363648_n](https://user-images.githubusercontent.com/56114419/71664350-f6404300-2d58-11ea-9f0d-8593d25ae19f.jpg)

The error was found here ->  `node_modules/modal-enhanced-react-native-web/dist/index.js:1:42664`

Do you have an idea of what could cause this issue ?
Thanks.

**Comment by kirrg001** [comment] 2020-02-09 09:30
Yep, doesn't work. I have the same issue.

**Comment by virgil9306** [comment] 2020-02-13 04:33
It probably works fine.

I would think that, since `document` is defined in the browser, if you open it in a browser it should work. That's probably why `document` is not found -- it's talking about the browser. So it makes sense the native app won't have the `document`.

So to use different code for "web browser" vs "iOS/Android app" you can do this:

```
import { Platform } from 'react-native';

...

if (Platform.OS !== 'web') {
    // render your MOBILE version of modal (regular React Native modal)
} else {
    // render your WEB version of modal (`react-native-web-modal`)
}
```

**Comment by virgil9306** [comment] 2020-02-26 06:14
BTW this is a duplicate of #13, #8

@rayandrews Can you close this issue? And do you have time to maintain this? Can you add more contributors?

**Comment by rayandrew** [comment] 2020-03-01 11:56
@virgil9306

I am currently rewriting this whole lib into typescript and support new API of React such as hooks, etc.
I am planning to add more contributors soon.
Still getting so many bugs. I hope I can release it soon.
The only problem lies within the React Native Modal Enhanced.
The backdrop and animation seems not working well with the new Typescript implementation on their side too.

For now I will keep opening this issue until this matter has been resolved.

Thank you!

**PS:
I am not in this organization again. 
I will release it on my own repo to make this library still compatible and overridable within the organization.**

**Comment by SkyAgency** [comment] 2020-04-19 21:47
My simple solution:

`
import { View, Text, StyleSheet, TouchableOpacity, ScrollView, Image, FlatList, Modal, Dimensions, Platform } from 'react-native';
import ModalWeb from 'modal-react-native-web';
...
const ModalModule = Platform.OS === 'web'?ModalWeb:Modal;
<ModalModule
  visible={isModalVisible}
  animationType="fade"
  transparent={true}
>
...
</ModalModule>
`

**Comment by nandorojo** [comment] 2020-09-27 19:18
@rayandrews are you still planning on maintaining this?

**Comment by rayandrew** [comment] 2020-09-28 02:25
@nandorojo yes for bug fixes. The feature is already considered complete. i will look into the bug fixes and pull requests later, still having other works to d. However, I hope I can do them this week.

I am planning on rewriting the modal (to use hooks etc, because react native have supported it) and removing obsolete API from React. The code is still buggy and cannot show the animations properly.

Sorry for the delay 😔

**Comment by rayandrew** [comment] 2020-10-14 08:47
modal is now supported in react native web.
there is no point on continuing this library.

https://github.com/necolas/react-native-web/releases/tag/0.14.0

I will close this

<blockquote><img src="https://avatars3.githubusercontent.com/u/239676?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="/necolas/react-native-web/releases/tag/0.14.0">Release 0.14.0 · necolas/react-native-web</a></strong></div><div>This is a relatively small release that introduces a couple of new features and makes a change to the default flexBasis value of View. There are no breaking API changes and it should be straight-fo...</div></blockquote>

**Closed as completed by rayandrew** 2020-10-14 08:47 UTC
